/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BusinessType = { 'fishery' : null } |
  { 'goatFarming' : null } |
  { 'poultry' : null } |
  { 'agriculture' : null };
export interface Case {
  'id' : CaseId,
  'status' : CaseStatus,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'businessType' : BusinessType,
  'description' : string,
  'photoUrl' : [] | [string],
  'updatedAt' : Timestamp,
  'assignedExpertId' : [] | [ExpertId],
  'adminNotes' : [] | [string],
}
export type CaseId = bigint;
export type CaseStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export interface CreateCaseInput {
  'businessType' : BusinessType,
  'description' : string,
  'photoUrl' : [] | [string],
}
export interface CreateExpertInput {
  'contactInfo' : string,
  'name' : string,
  'specialization' : Specialization,
}
export interface CreateResourceInput {
  'name' : string,
  'isAvailable' : boolean,
  'description' : string,
  'category' : ResourceCategory,
}
export interface CreateSupplyRequestInput {
  'resourceId' : ResourceId,
  'deliveryLocation' : string,
  'quantity' : bigint,
}
export interface Expert {
  'id' : ExpertId,
  'contactInfo' : string,
  'assignedCasesCount' : bigint,
  'name' : string,
  'createdAt' : Timestamp,
  'isActive' : boolean,
  'specialization' : Specialization,
}
export type ExpertId = bigint;
export interface Resource {
  'id' : ResourceId,
  'name' : string,
  'isAvailable' : boolean,
  'description' : string,
  'category' : ResourceCategory,
}
export type ResourceCategory = { 'poultry' : null } |
  { 'fish' : null } |
  { 'goat' : null } |
  { 'seeds' : null };
export type ResourceId = bigint;
export interface SaveProfileInput {
  'name' : string,
  'businessType' : BusinessType,
  'mobile' : string,
  'location' : string,
}
export type Specialization = { 'fishery' : null } |
  { 'goatFarming' : null } |
  { 'poultry' : null } |
  { 'agriculture' : null };
export interface SupplyRequest {
  'id' : SupplyRequestId,
  'status' : SupplyRequestStatus,
  'resourceId' : ResourceId,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'deliveryLocation' : string,
  'quantity' : bigint,
}
export type SupplyRequestId = bigint;
export type SupplyRequestStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'processing' : null };
export type Timestamp = bigint;
export interface UpdateCaseInput {
  'status' : [] | [CaseStatus],
  'assignedExpertId' : [] | [ExpertId],
  'adminNotes' : [] | [string],
}
export type UserId = Principal;
export interface UserProfile {
  'id' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'businessType' : BusinessType,
  'mobile' : string,
  'location' : string,
}
export interface _SERVICE {
  'addExpert' : ActorMethod<[CreateExpertInput], Expert>,
  'addResource' : ActorMethod<[CreateResourceInput], Resource>,
  /**
   * / Check if caller is an admin
   */
  'checkIsAdmin' : ActorMethod<[], boolean>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCase' : ActorMethod<[CaseId], [] | [Case]>,
  'getExpert' : ActorMethod<[ExpertId], [] | [Expert]>,
  'getMyCases' : ActorMethod<[], Array<Case>>,
  'getMySupplyRequests' : ActorMethod<[], Array<SupplyRequest>>,
  'getResource' : ActorMethod<[ResourceId], [] | [Resource]>,
  'getSupplyRequest' : ActorMethod<[SupplyRequestId], [] | [SupplyRequest]>,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  /**
   * / Grant admin role to a principal (only existing admins or first caller)
   */
  'grantAdmin' : ActorMethod<[Principal], undefined>,
  'listAllCases' : ActorMethod<[], Array<Case>>,
  'listAllSupplyRequests' : ActorMethod<[], Array<SupplyRequest>>,
  'listExperts' : ActorMethod<[], Array<Expert>>,
  'listResources' : ActorMethod<[], Array<Resource>>,
  'listUserProfiles' : ActorMethod<[], Array<UserProfile>>,
  'saveCallerUserProfile' : ActorMethod<[SaveProfileInput], undefined>,
  'setExpertActive' : ActorMethod<[ExpertId, boolean], [] | [Expert]>,
  'submitCase' : ActorMethod<[CreateCaseInput], Case>,
  'submitSupplyRequest' : ActorMethod<
    [CreateSupplyRequestInput],
    SupplyRequest
  >,
  'updateCase' : ActorMethod<[CaseId, UpdateCaseInput], [] | [Case]>,
  'updateSupplyRequestStatus' : ActorMethod<
    [SupplyRequestId, SupplyRequestStatus],
    [] | [SupplyRequest]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];