/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Specialization = IDL.Variant({
  'fishery' : IDL.Null,
  'goatFarming' : IDL.Null,
  'poultry' : IDL.Null,
  'agriculture' : IDL.Null,
});
export const CreateExpertInput = IDL.Record({
  'contactInfo' : IDL.Text,
  'name' : IDL.Text,
  'specialization' : Specialization,
});
export const ExpertId = IDL.Nat;
export const Timestamp = IDL.Int;
export const Expert = IDL.Record({
  'id' : ExpertId,
  'contactInfo' : IDL.Text,
  'assignedCasesCount' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'isActive' : IDL.Bool,
  'specialization' : Specialization,
});
export const ResourceCategory = IDL.Variant({
  'poultry' : IDL.Null,
  'fish' : IDL.Null,
  'goat' : IDL.Null,
  'seeds' : IDL.Null,
});
export const CreateResourceInput = IDL.Record({
  'name' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'category' : ResourceCategory,
});
export const ResourceId = IDL.Nat;
export const Resource = IDL.Record({
  'id' : ResourceId,
  'name' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'category' : ResourceCategory,
});
export const UserId = IDL.Principal;
export const BusinessType = IDL.Variant({
  'fishery' : IDL.Null,
  'goatFarming' : IDL.Null,
  'poultry' : IDL.Null,
  'agriculture' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'id' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'businessType' : BusinessType,
  'mobile' : IDL.Text,
  'location' : IDL.Text,
});
export const CaseId = IDL.Nat;
export const CaseStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Case = IDL.Record({
  'id' : CaseId,
  'status' : CaseStatus,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'businessType' : BusinessType,
  'description' : IDL.Text,
  'photoUrl' : IDL.Opt(IDL.Text),
  'updatedAt' : Timestamp,
  'assignedExpertId' : IDL.Opt(ExpertId),
  'adminNotes' : IDL.Opt(IDL.Text),
});
export const SupplyRequestId = IDL.Nat;
export const SupplyRequestStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'processing' : IDL.Null,
});
export const SupplyRequest = IDL.Record({
  'id' : SupplyRequestId,
  'status' : SupplyRequestStatus,
  'resourceId' : ResourceId,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'deliveryLocation' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const SaveProfileInput = IDL.Record({
  'name' : IDL.Text,
  'businessType' : BusinessType,
  'mobile' : IDL.Text,
  'location' : IDL.Text,
});
export const CreateCaseInput = IDL.Record({
  'businessType' : BusinessType,
  'description' : IDL.Text,
  'photoUrl' : IDL.Opt(IDL.Text),
});
export const CreateSupplyRequestInput = IDL.Record({
  'resourceId' : ResourceId,
  'deliveryLocation' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const UpdateCaseInput = IDL.Record({
  'status' : IDL.Opt(CaseStatus),
  'assignedExpertId' : IDL.Opt(ExpertId),
  'adminNotes' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'addExpert' : IDL.Func([CreateExpertInput], [Expert], []),
  'addResource' : IDL.Func([CreateResourceInput], [Resource], []),
  'checkIsAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCase' : IDL.Func([CaseId], [IDL.Opt(Case)], ['query']),
  'getExpert' : IDL.Func([ExpertId], [IDL.Opt(Expert)], ['query']),
  'getMyCases' : IDL.Func([], [IDL.Vec(Case)], ['query']),
  'getMySupplyRequests' : IDL.Func([], [IDL.Vec(SupplyRequest)], ['query']),
  'getResource' : IDL.Func([ResourceId], [IDL.Opt(Resource)], ['query']),
  'getSupplyRequest' : IDL.Func(
      [SupplyRequestId],
      [IDL.Opt(SupplyRequest)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'grantAdmin' : IDL.Func([IDL.Principal], [], []),
  'listAllCases' : IDL.Func([], [IDL.Vec(Case)], ['query']),
  'listAllSupplyRequests' : IDL.Func([], [IDL.Vec(SupplyRequest)], ['query']),
  'listExperts' : IDL.Func([], [IDL.Vec(Expert)], ['query']),
  'listResources' : IDL.Func([], [IDL.Vec(Resource)], ['query']),
  'listUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'saveCallerUserProfile' : IDL.Func([SaveProfileInput], [], []),
  'setExpertActive' : IDL.Func([ExpertId, IDL.Bool], [IDL.Opt(Expert)], []),
  'submitCase' : IDL.Func([CreateCaseInput], [Case], []),
  'submitSupplyRequest' : IDL.Func(
      [CreateSupplyRequestInput],
      [SupplyRequest],
      [],
    ),
  'updateCase' : IDL.Func([CaseId, UpdateCaseInput], [IDL.Opt(Case)], []),
  'updateSupplyRequestStatus' : IDL.Func(
      [SupplyRequestId, SupplyRequestStatus],
      [IDL.Opt(SupplyRequest)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Specialization = IDL.Variant({
    'fishery' : IDL.Null,
    'goatFarming' : IDL.Null,
    'poultry' : IDL.Null,
    'agriculture' : IDL.Null,
  });
  const CreateExpertInput = IDL.Record({
    'contactInfo' : IDL.Text,
    'name' : IDL.Text,
    'specialization' : Specialization,
  });
  const ExpertId = IDL.Nat;
  const Timestamp = IDL.Int;
  const Expert = IDL.Record({
    'id' : ExpertId,
    'contactInfo' : IDL.Text,
    'assignedCasesCount' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'isActive' : IDL.Bool,
    'specialization' : Specialization,
  });
  const ResourceCategory = IDL.Variant({
    'poultry' : IDL.Null,
    'fish' : IDL.Null,
    'goat' : IDL.Null,
    'seeds' : IDL.Null,
  });
  const CreateResourceInput = IDL.Record({
    'name' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'category' : ResourceCategory,
  });
  const ResourceId = IDL.Nat;
  const Resource = IDL.Record({
    'id' : ResourceId,
    'name' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'category' : ResourceCategory,
  });
  const UserId = IDL.Principal;
  const BusinessType = IDL.Variant({
    'fishery' : IDL.Null,
    'goatFarming' : IDL.Null,
    'poultry' : IDL.Null,
    'agriculture' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'id' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'businessType' : BusinessType,
    'mobile' : IDL.Text,
    'location' : IDL.Text,
  });
  const CaseId = IDL.Nat;
  const CaseStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Case = IDL.Record({
    'id' : CaseId,
    'status' : CaseStatus,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'businessType' : BusinessType,
    'description' : IDL.Text,
    'photoUrl' : IDL.Opt(IDL.Text),
    'updatedAt' : Timestamp,
    'assignedExpertId' : IDL.Opt(ExpertId),
    'adminNotes' : IDL.Opt(IDL.Text),
  });
  const SupplyRequestId = IDL.Nat;
  const SupplyRequestStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'processing' : IDL.Null,
  });
  const SupplyRequest = IDL.Record({
    'id' : SupplyRequestId,
    'status' : SupplyRequestStatus,
    'resourceId' : ResourceId,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'deliveryLocation' : IDL.Text,
    'quantity' : IDL.Nat,
  });
  const SaveProfileInput = IDL.Record({
    'name' : IDL.Text,
    'businessType' : BusinessType,
    'mobile' : IDL.Text,
    'location' : IDL.Text,
  });
  const CreateCaseInput = IDL.Record({
    'businessType' : BusinessType,
    'description' : IDL.Text,
    'photoUrl' : IDL.Opt(IDL.Text),
  });
  const CreateSupplyRequestInput = IDL.Record({
    'resourceId' : ResourceId,
    'deliveryLocation' : IDL.Text,
    'quantity' : IDL.Nat,
  });
  const UpdateCaseInput = IDL.Record({
    'status' : IDL.Opt(CaseStatus),
    'assignedExpertId' : IDL.Opt(ExpertId),
    'adminNotes' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'addExpert' : IDL.Func([CreateExpertInput], [Expert], []),
    'addResource' : IDL.Func([CreateResourceInput], [Resource], []),
    'checkIsAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCase' : IDL.Func([CaseId], [IDL.Opt(Case)], ['query']),
    'getExpert' : IDL.Func([ExpertId], [IDL.Opt(Expert)], ['query']),
    'getMyCases' : IDL.Func([], [IDL.Vec(Case)], ['query']),
    'getMySupplyRequests' : IDL.Func([], [IDL.Vec(SupplyRequest)], ['query']),
    'getResource' : IDL.Func([ResourceId], [IDL.Opt(Resource)], ['query']),
    'getSupplyRequest' : IDL.Func(
        [SupplyRequestId],
        [IDL.Opt(SupplyRequest)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'grantAdmin' : IDL.Func([IDL.Principal], [], []),
    'listAllCases' : IDL.Func([], [IDL.Vec(Case)], ['query']),
    'listAllSupplyRequests' : IDL.Func([], [IDL.Vec(SupplyRequest)], ['query']),
    'listExperts' : IDL.Func([], [IDL.Vec(Expert)], ['query']),
    'listResources' : IDL.Func([], [IDL.Vec(Resource)], ['query']),
    'listUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'saveCallerUserProfile' : IDL.Func([SaveProfileInput], [], []),
    'setExpertActive' : IDL.Func([ExpertId, IDL.Bool], [IDL.Opt(Expert)], []),
    'submitCase' : IDL.Func([CreateCaseInput], [Case], []),
    'submitSupplyRequest' : IDL.Func(
        [CreateSupplyRequestInput],
        [SupplyRequest],
        [],
      ),
    'updateCase' : IDL.Func([CaseId, UpdateCaseInput], [IDL.Opt(Case)], []),
    'updateSupplyRequestStatus' : IDL.Func(
        [SupplyRequestId, SupplyRequestStatus],
        [IDL.Opt(SupplyRequest)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };