/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Specialization = IDL.Variant({
  'fishery' : IDL.Null,
  'goatFarming' : IDL.Null,
  'poultry' : IDL.Null,
  'agriculture' : IDL.Null,
});
export const CreateExpertInput = IDL.Record({
  'contactInfo' : IDL.Text,
  'name' : IDL.Text,
  'specialization' : Specialization,
});
export const ExpertId = IDL.Nat;
export const Timestamp = IDL.Int;
export const Expert = IDL.Record({
  'id' : ExpertId,
  'contactInfo' : IDL.Text,
  'assignedCasesCount' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'isActive' : IDL.Bool,
  'specialization' : Specialization,
});
export const ResourceCategory = IDL.Variant({
  'poultry' : IDL.Null,
  'fish' : IDL.Null,
  'goat' : IDL.Null,
  'seeds' : IDL.Null,
});
export const CreateResourceInput = IDL.Record({
  'name' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'category' : ResourceCategory,
});
export const ResourceId = IDL.Nat;
export const Resource = IDL.Record({
  'id' : ResourceId,
  'name' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'category' : ResourceCategory,
});
export const BusinessType = IDL.Variant({
  'fishery' : IDL.Null,
  'goatFarming' : IDL.Null,
  'poultry' : IDL.Null,
  'agriculture' : IDL.Null,
});
export const CreateTrainingInput = IDL.Record({
  'title' : IDL.Text,
  'duration' : IDL.Text,
  'description' : IDL.Text,
  'sector' : BusinessType,
});
export const TrainingId = IDL.Nat;
export const TrainingProgram = IDL.Record({
  'id' : TrainingId,
  'title' : IDL.Text,
  'duration' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'sector' : BusinessType,
  'isActive' : IDL.Bool,
});
export const EnrollTrainingInput = IDL.Record({ 'programId' : TrainingId });
export const EnrollmentId = IDL.Nat;
export const EnrollmentStatus = IDL.Variant({
  'enrolled' : IDL.Null,
  'completed' : IDL.Null,
  'ongoing' : IDL.Null,
});
export const UserId = IDL.Principal;
export const TrainingEnrollment = IDL.Record({
  'id' : EnrollmentId,
  'status' : EnrollmentStatus,
  'userId' : UserId,
  'updatedAt' : Timestamp,
  'enrolledAt' : Timestamp,
  'programId' : TrainingId,
});
export const UserProfile = IDL.Record({
  'id' : UserId,
  'aiRecommendation' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'whatsapp' : IDL.Text,
  'businessType' : BusinessType,
  'mobile' : IDL.Text,
  'location' : IDL.Text,
});
export const CaseId = IDL.Nat;
export const CaseStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Case = IDL.Record({
  'id' : CaseId,
  'status' : CaseStatus,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'businessType' : BusinessType,
  'description' : IDL.Text,
  'photoUrl' : IDL.Opt(IDL.Text),
  'updatedAt' : Timestamp,
  'assignedExpertId' : IDL.Opt(ExpertId),
  'adminNotes' : IDL.Opt(IDL.Text),
});
export const AIQuizResult = IDL.Record({
  'reasons' : IDL.Vec(IDL.Text),
  'createdAt' : Timestamp,
  'businessType' : BusinessType,
  'confidence' : IDL.Text,
});
export const ContactLeadId = IDL.Nat;
export const ContactLead = IDL.Record({
  'id' : ContactLeadId,
  'status' : IDL.Text,
  'userId' : IDL.Opt(UserId),
  'name' : IDL.Text,
  'whatsapp' : IDL.Text,
  'submittedAt' : Timestamp,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'location' : IDL.Text,
  'problem' : IDL.Text,
});
export const PremiumRequestId = IDL.Nat;
export const PremiumRequest = IDL.Record({
  'id' : PremiumRequestId,
  'userId' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'email' : IDL.Text,
  'isContacted' : IDL.Bool,
  'mobile' : IDL.Text,
  'reason' : IDL.Text,
});
export const SupplyRequestId = IDL.Nat;
export const SupplyRequestStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'processing' : IDL.Null,
});
export const SupplyRequest = IDL.Record({
  'id' : SupplyRequestId,
  'status' : SupplyRequestStatus,
  'resourceId' : ResourceId,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'deliveryLocation' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const SaveProfileInput = IDL.Record({
  'aiRecommendation' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'whatsapp' : IDL.Text,
  'businessType' : BusinessType,
  'mobile' : IDL.Text,
  'location' : IDL.Text,
});
export const QuizAnswers = IDL.Record({
  'interest' : IDL.Text,
  'experience' : IDL.Text,
  'budget' : IDL.Text,
  'location' : IDL.Text,
  'landAvailable' : IDL.Text,
});
export const CreateCaseInput = IDL.Record({
  'businessType' : BusinessType,
  'description' : IDL.Text,
  'photoUrl' : IDL.Opt(IDL.Text),
});
export const CreateContactLeadInput = IDL.Record({
  'name' : IDL.Text,
  'whatsapp' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'location' : IDL.Text,
  'problem' : IDL.Text,
});
export const CreatePremiumRequestInput = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'mobile' : IDL.Text,
  'reason' : IDL.Text,
});
export const CreateSupplyRequestInput = IDL.Record({
  'resourceId' : ResourceId,
  'deliveryLocation' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const UpdateCaseInput = IDL.Record({
  'status' : IDL.Opt(CaseStatus),
  'assignedExpertId' : IDL.Opt(ExpertId),
  'adminNotes' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'addExpert' : IDL.Func([CreateExpertInput], [Expert], []),
  'addResource' : IDL.Func([CreateResourceInput], [Resource], []),
  'checkIsAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'createTrainingProgram' : IDL.Func(
      [CreateTrainingInput],
      [TrainingProgram],
      [],
    ),
  'enrollInTraining' : IDL.Func(
      [EnrollTrainingInput],
      [TrainingEnrollment],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCase' : IDL.Func([CaseId], [IDL.Opt(Case)], ['query']),
  'getExpert' : IDL.Func([ExpertId], [IDL.Opt(Expert)], ['query']),
  'getMyAIQuizResult' : IDL.Func([], [IDL.Opt(AIQuizResult)], ['query']),
  'getMyCases' : IDL.Func([], [IDL.Vec(Case)], ['query']),
  'getMyContactLeads' : IDL.Func([], [IDL.Vec(ContactLead)], ['query']),
  'getMyPremiumRequest' : IDL.Func([], [IDL.Opt(PremiumRequest)], ['query']),
  'getMySupplyRequests' : IDL.Func([], [IDL.Vec(SupplyRequest)], ['query']),
  'getMyTrainingEnrollments' : IDL.Func(
      [],
      [IDL.Vec(TrainingEnrollment)],
      ['query'],
    ),
  'getProgramEnrollments' : IDL.Func(
      [TrainingId],
      [IDL.Vec(TrainingEnrollment)],
      ['query'],
    ),
  'getResource' : IDL.Func([ResourceId], [IDL.Opt(Resource)], ['query']),
  'getSupplyRequest' : IDL.Func(
      [SupplyRequestId],
      [IDL.Opt(SupplyRequest)],
      ['query'],
    ),
  'getTrainingProgram' : IDL.Func(
      [TrainingId],
      [IDL.Opt(TrainingProgram)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'grantAdmin' : IDL.Func([IDL.Principal], [], []),
  'listAllCases' : IDL.Func([], [IDL.Vec(Case)], ['query']),
  'listAllContactLeads' : IDL.Func([], [IDL.Vec(ContactLead)], ['query']),
  'listAllSupplyRequests' : IDL.Func([], [IDL.Vec(SupplyRequest)], ['query']),
  'listExperts' : IDL.Func([], [IDL.Vec(Expert)], ['query']),
  'listPremiumRequests' : IDL.Func([], [IDL.Vec(PremiumRequest)], ['query']),
  'listResources' : IDL.Func([], [IDL.Vec(Resource)], ['query']),
  'listTrainingPrograms' : IDL.Func([], [IDL.Vec(TrainingProgram)], ['query']),
  'listUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'markPremiumRequestContacted' : IDL.Func([PremiumRequestId], [], []),
  'saveCallerUserProfile' : IDL.Func([SaveProfileInput], [], []),
  'setExpertActive' : IDL.Func([ExpertId, IDL.Bool], [IDL.Opt(Expert)], []),
  'submitAIQuiz' : IDL.Func([QuizAnswers], [AIQuizResult], []),
  'submitCase' : IDL.Func([CreateCaseInput], [Case], []),
  'submitContactLead' : IDL.Func([CreateContactLeadInput], [IDL.Nat], []),
  'submitPremiumRequest' : IDL.Func(
      [CreatePremiumRequestInput],
      [PremiumRequest],
      [],
    ),
  'submitSupplyRequest' : IDL.Func(
      [CreateSupplyRequestInput],
      [SupplyRequest],
      [],
    ),
  'toggleTrainingProgramActive' : IDL.Func([TrainingId], [], []),
  'updateCase' : IDL.Func([CaseId, UpdateCaseInput], [IDL.Opt(Case)], []),
  'updateSupplyRequestStatus' : IDL.Func(
      [SupplyRequestId, SupplyRequestStatus],
      [IDL.Opt(SupplyRequest)],
      [],
    ),
  'updateTrainingEnrollmentStatus' : IDL.Func(
      [EnrollmentId, EnrollmentStatus],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Specialization = IDL.Variant({
    'fishery' : IDL.Null,
    'goatFarming' : IDL.Null,
    'poultry' : IDL.Null,
    'agriculture' : IDL.Null,
  });
  const CreateExpertInput = IDL.Record({
    'contactInfo' : IDL.Text,
    'name' : IDL.Text,
    'specialization' : Specialization,
  });
  const ExpertId = IDL.Nat;
  const Timestamp = IDL.Int;
  const Expert = IDL.Record({
    'id' : ExpertId,
    'contactInfo' : IDL.Text,
    'assignedCasesCount' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'isActive' : IDL.Bool,
    'specialization' : Specialization,
  });
  const ResourceCategory = IDL.Variant({
    'poultry' : IDL.Null,
    'fish' : IDL.Null,
    'goat' : IDL.Null,
    'seeds' : IDL.Null,
  });
  const CreateResourceInput = IDL.Record({
    'name' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'category' : ResourceCategory,
  });
  const ResourceId = IDL.Nat;
  const Resource = IDL.Record({
    'id' : ResourceId,
    'name' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'category' : ResourceCategory,
  });
  const BusinessType = IDL.Variant({
    'fishery' : IDL.Null,
    'goatFarming' : IDL.Null,
    'poultry' : IDL.Null,
    'agriculture' : IDL.Null,
  });
  const CreateTrainingInput = IDL.Record({
    'title' : IDL.Text,
    'duration' : IDL.Text,
    'description' : IDL.Text,
    'sector' : BusinessType,
  });
  const TrainingId = IDL.Nat;
  const TrainingProgram = IDL.Record({
    'id' : TrainingId,
    'title' : IDL.Text,
    'duration' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'sector' : BusinessType,
    'isActive' : IDL.Bool,
  });
  const EnrollTrainingInput = IDL.Record({ 'programId' : TrainingId });
  const EnrollmentId = IDL.Nat;
  const EnrollmentStatus = IDL.Variant({
    'enrolled' : IDL.Null,
    'completed' : IDL.Null,
    'ongoing' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const TrainingEnrollment = IDL.Record({
    'id' : EnrollmentId,
    'status' : EnrollmentStatus,
    'userId' : UserId,
    'updatedAt' : Timestamp,
    'enrolledAt' : Timestamp,
    'programId' : TrainingId,
  });
  const UserProfile = IDL.Record({
    'id' : UserId,
    'aiRecommendation' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'whatsapp' : IDL.Text,
    'businessType' : BusinessType,
    'mobile' : IDL.Text,
    'location' : IDL.Text,
  });
  const CaseId = IDL.Nat;
  const CaseStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Case = IDL.Record({
    'id' : CaseId,
    'status' : CaseStatus,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'businessType' : BusinessType,
    'description' : IDL.Text,
    'photoUrl' : IDL.Opt(IDL.Text),
    'updatedAt' : Timestamp,
    'assignedExpertId' : IDL.Opt(ExpertId),
    'adminNotes' : IDL.Opt(IDL.Text),
  });
  const AIQuizResult = IDL.Record({
    'reasons' : IDL.Vec(IDL.Text),
    'createdAt' : Timestamp,
    'businessType' : BusinessType,
    'confidence' : IDL.Text,
  });
  const ContactLeadId = IDL.Nat;
  const ContactLead = IDL.Record({
    'id' : ContactLeadId,
    'status' : IDL.Text,
    'userId' : IDL.Opt(UserId),
    'name' : IDL.Text,
    'whatsapp' : IDL.Text,
    'submittedAt' : Timestamp,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'location' : IDL.Text,
    'problem' : IDL.Text,
  });
  const PremiumRequestId = IDL.Nat;
  const PremiumRequest = IDL.Record({
    'id' : PremiumRequestId,
    'userId' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'email' : IDL.Text,
    'isContacted' : IDL.Bool,
    'mobile' : IDL.Text,
    'reason' : IDL.Text,
  });
  const SupplyRequestId = IDL.Nat;
  const SupplyRequestStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'processing' : IDL.Null,
  });
  const SupplyRequest = IDL.Record({
    'id' : SupplyRequestId,
    'status' : SupplyRequestStatus,
    'resourceId' : ResourceId,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'deliveryLocation' : IDL.Text,
    'quantity' : IDL.Nat,
  });
  const SaveProfileInput = IDL.Record({
    'aiRecommendation' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'whatsapp' : IDL.Text,
    'businessType' : BusinessType,
    'mobile' : IDL.Text,
    'location' : IDL.Text,
  });
  const QuizAnswers = IDL.Record({
    'interest' : IDL.Text,
    'experience' : IDL.Text,
    'budget' : IDL.Text,
    'location' : IDL.Text,
    'landAvailable' : IDL.Text,
  });
  const CreateCaseInput = IDL.Record({
    'businessType' : BusinessType,
    'description' : IDL.Text,
    'photoUrl' : IDL.Opt(IDL.Text),
  });
  const CreateContactLeadInput = IDL.Record({
    'name' : IDL.Text,
    'whatsapp' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'location' : IDL.Text,
    'problem' : IDL.Text,
  });
  const CreatePremiumRequestInput = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'mobile' : IDL.Text,
    'reason' : IDL.Text,
  });
  const CreateSupplyRequestInput = IDL.Record({
    'resourceId' : ResourceId,
    'deliveryLocation' : IDL.Text,
    'quantity' : IDL.Nat,
  });
  const UpdateCaseInput = IDL.Record({
    'status' : IDL.Opt(CaseStatus),
    'assignedExpertId' : IDL.Opt(ExpertId),
    'adminNotes' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'addExpert' : IDL.Func([CreateExpertInput], [Expert], []),
    'addResource' : IDL.Func([CreateResourceInput], [Resource], []),
    'checkIsAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'createTrainingProgram' : IDL.Func(
        [CreateTrainingInput],
        [TrainingProgram],
        [],
      ),
    'enrollInTraining' : IDL.Func(
        [EnrollTrainingInput],
        [TrainingEnrollment],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCase' : IDL.Func([CaseId], [IDL.Opt(Case)], ['query']),
    'getExpert' : IDL.Func([ExpertId], [IDL.Opt(Expert)], ['query']),
    'getMyAIQuizResult' : IDL.Func([], [IDL.Opt(AIQuizResult)], ['query']),
    'getMyCases' : IDL.Func([], [IDL.Vec(Case)], ['query']),
    'getMyContactLeads' : IDL.Func([], [IDL.Vec(ContactLead)], ['query']),
    'getMyPremiumRequest' : IDL.Func([], [IDL.Opt(PremiumRequest)], ['query']),
    'getMySupplyRequests' : IDL.Func([], [IDL.Vec(SupplyRequest)], ['query']),
    'getMyTrainingEnrollments' : IDL.Func(
        [],
        [IDL.Vec(TrainingEnrollment)],
        ['query'],
      ),
    'getProgramEnrollments' : IDL.Func(
        [TrainingId],
        [IDL.Vec(TrainingEnrollment)],
        ['query'],
      ),
    'getResource' : IDL.Func([ResourceId], [IDL.Opt(Resource)], ['query']),
    'getSupplyRequest' : IDL.Func(
        [SupplyRequestId],
        [IDL.Opt(SupplyRequest)],
        ['query'],
      ),
    'getTrainingProgram' : IDL.Func(
        [TrainingId],
        [IDL.Opt(TrainingProgram)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'grantAdmin' : IDL.Func([IDL.Principal], [], []),
    'listAllCases' : IDL.Func([], [IDL.Vec(Case)], ['query']),
    'listAllContactLeads' : IDL.Func([], [IDL.Vec(ContactLead)], ['query']),
    'listAllSupplyRequests' : IDL.Func([], [IDL.Vec(SupplyRequest)], ['query']),
    'listExperts' : IDL.Func([], [IDL.Vec(Expert)], ['query']),
    'listPremiumRequests' : IDL.Func([], [IDL.Vec(PremiumRequest)], ['query']),
    'listResources' : IDL.Func([], [IDL.Vec(Resource)], ['query']),
    'listTrainingPrograms' : IDL.Func(
        [],
        [IDL.Vec(TrainingProgram)],
        ['query'],
      ),
    'listUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'markPremiumRequestContacted' : IDL.Func([PremiumRequestId], [], []),
    'saveCallerUserProfile' : IDL.Func([SaveProfileInput], [], []),
    'setExpertActive' : IDL.Func([ExpertId, IDL.Bool], [IDL.Opt(Expert)], []),
    'submitAIQuiz' : IDL.Func([QuizAnswers], [AIQuizResult], []),
    'submitCase' : IDL.Func([CreateCaseInput], [Case], []),
    'submitContactLead' : IDL.Func([CreateContactLeadInput], [IDL.Nat], []),
    'submitPremiumRequest' : IDL.Func(
        [CreatePremiumRequestInput],
        [PremiumRequest],
        [],
      ),
    'submitSupplyRequest' : IDL.Func(
        [CreateSupplyRequestInput],
        [SupplyRequest],
        [],
      ),
    'toggleTrainingProgramActive' : IDL.Func([TrainingId], [], []),
    'updateCase' : IDL.Func([CaseId, UpdateCaseInput], [IDL.Opt(Case)], []),
    'updateSupplyRequestStatus' : IDL.Func(
        [SupplyRequestId, SupplyRequestStatus],
        [IDL.Opt(SupplyRequest)],
        [],
      ),
    'updateTrainingEnrollmentStatus' : IDL.Func(
        [EnrollmentId, EnrollmentStatus],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };