/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SaveProfileInput {
    name: string;
    businessType: BusinessType;
    mobile: string;
    location: string;
}
export type Timestamp = bigint;
export interface Case {
    id: CaseId;
    status: CaseStatus;
    userId: UserId;
    createdAt: Timestamp;
    businessType: BusinessType;
    description: string;
    photoUrl?: string;
    updatedAt: Timestamp;
    assignedExpertId?: ExpertId;
    adminNotes?: string;
}
export interface CreateCaseInput {
    businessType: BusinessType;
    description: string;
    photoUrl?: string;
}
export interface CreateExpertInput {
    contactInfo: string;
    name: string;
    specialization: Specialization;
}
export interface CreateResourceInput {
    name: string;
    isAvailable: boolean;
    description: string;
    category: ResourceCategory;
}
export interface Expert {
    id: ExpertId;
    contactInfo: string;
    assignedCasesCount: bigint;
    name: string;
    createdAt: Timestamp;
    isActive: boolean;
    specialization: Specialization;
}
export interface CreateSupplyRequestInput {
    resourceId: ResourceId;
    deliveryLocation: string;
    quantity: bigint;
}
export type UserId = Principal;
export interface UpdateCaseInput {
    status?: CaseStatus;
    assignedExpertId?: ExpertId;
    adminNotes?: string;
}
export type ExpertId = bigint;
export type CaseId = bigint;
export interface Resource {
    id: ResourceId;
    name: string;
    isAvailable: boolean;
    description: string;
    category: ResourceCategory;
}
export interface SupplyRequest {
    id: SupplyRequestId;
    status: SupplyRequestStatus;
    resourceId: ResourceId;
    userId: UserId;
    createdAt: Timestamp;
    deliveryLocation: string;
    quantity: bigint;
}
export type ResourceId = bigint;
export type SupplyRequestId = bigint;
export interface UserProfile {
    id: UserId;
    name: string;
    createdAt: Timestamp;
    businessType: BusinessType;
    mobile: string;
    location: string;
}
export enum BusinessType {
    fishery = "fishery",
    goatFarming = "goatFarming",
    poultry = "poultry",
    agriculture = "agriculture"
}
export enum CaseStatus {
    pending = "pending",
    completed = "completed",
    inProgress = "inProgress"
}
export enum ResourceCategory {
    poultry = "poultry",
    fish = "fish",
    goat = "goat",
    seeds = "seeds"
}
export enum SupplyRequestStatus {
    cancelled = "cancelled",
    pending = "pending",
    delivered = "delivered",
    processing = "processing"
}
export interface backendInterface {
    addExpert(input: CreateExpertInput): Promise<Expert>;
    addResource(input: CreateResourceInput): Promise<Resource>;
    /**
     * / Check if caller is an admin
     */
    checkIsAdmin(): Promise<boolean>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCase(id: CaseId): Promise<Case | null>;
    getExpert(id: ExpertId): Promise<Expert | null>;
    getMyCases(): Promise<Array<Case>>;
    getMySupplyRequests(): Promise<Array<SupplyRequest>>;
    getResource(id: ResourceId): Promise<Resource | null>;
    getSupplyRequest(id: SupplyRequestId): Promise<SupplyRequest | null>;
    getUserProfile(user: UserId): Promise<UserProfile | null>;
    /**
     * / Grant admin role to a principal (only existing admins or first caller)
     */
    grantAdmin(user: Principal): Promise<void>;
    listAllCases(): Promise<Array<Case>>;
    listAllSupplyRequests(): Promise<Array<SupplyRequest>>;
    listExperts(): Promise<Array<Expert>>;
    listResources(): Promise<Array<Resource>>;
    listUserProfiles(): Promise<Array<UserProfile>>;
    saveCallerUserProfile(input: SaveProfileInput): Promise<void>;
    setExpertActive(id: ExpertId, isActive: boolean): Promise<Expert | null>;
    submitCase(input: CreateCaseInput): Promise<Case>;
    submitSupplyRequest(input: CreateSupplyRequestInput): Promise<SupplyRequest>;
    updateCase(id: CaseId, input: UpdateCaseInput): Promise<Case | null>;
    updateSupplyRequestStatus(id: SupplyRequestId, status: SupplyRequestStatus): Promise<SupplyRequest | null>;
}
import type { BusinessType as _BusinessType, Case as _Case, CaseId as _CaseId, CaseStatus as _CaseStatus, CreateCaseInput as _CreateCaseInput, CreateExpertInput as _CreateExpertInput, CreateResourceInput as _CreateResourceInput, Expert as _Expert, ExpertId as _ExpertId, Resource as _Resource, ResourceCategory as _ResourceCategory, ResourceId as _ResourceId, SaveProfileInput as _SaveProfileInput, Specialization as _Specialization, SupplyRequest as _SupplyRequest, SupplyRequestId as _SupplyRequestId, SupplyRequestStatus as _SupplyRequestStatus, Timestamp as _Timestamp, UpdateCaseInput as _UpdateCaseInput, UserId as _UserId, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addExpert(arg0: CreateExpertInput): Promise<Expert> {
        if (this.processError) {
            try {
                const result = await this.actor.addExpert(to_candid_CreateExpertInput_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Expert_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExpert(to_candid_CreateExpertInput_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Expert_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async addResource(arg0: CreateResourceInput): Promise<Resource> {
        if (this.processError) {
            try {
                const result = await this.actor.addResource(to_candid_CreateResourceInput_n9(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Resource_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addResource(to_candid_CreateResourceInput_n9(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Resource_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async checkIsAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.checkIsAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkIsAdmin();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCase(arg0: CaseId): Promise<Case | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCase(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCase(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExpert(arg0: ExpertId): Promise<Expert | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpert(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpert(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyCases(): Promise<Array<Case>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyCases();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyCases();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMySupplyRequests(): Promise<Array<SupplyRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMySupplyRequests();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMySupplyRequests();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResource(arg0: ResourceId): Promise<Resource | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getResource(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResource(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSupplyRequest(arg0: SupplyRequestId): Promise<SupplyRequest | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSupplyRequest(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSupplyRequest(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: UserId): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async grantAdmin(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.grantAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.grantAdmin(arg0);
            return result;
        }
    }
    async listAllCases(): Promise<Array<Case>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllCases();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllCases();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAllSupplyRequests(): Promise<Array<SupplyRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllSupplyRequests();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllSupplyRequests();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async listExperts(): Promise<Array<Expert>> {
        if (this.processError) {
            try {
                const result = await this.actor.listExperts();
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listExperts();
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async listResources(): Promise<Array<Resource>> {
        if (this.processError) {
            try {
                const result = await this.actor.listResources();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listResources();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async listUserProfiles(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUserProfiles();
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUserProfiles();
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: SaveProfileInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_SaveProfileInput_n40(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_SaveProfileInput_n40(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setExpertActive(arg0: ExpertId, arg1: boolean): Promise<Expert | null> {
        if (this.processError) {
            try {
                const result = await this.actor.setExpertActive(arg0, arg1);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setExpertActive(arg0, arg1);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitCase(arg0: CreateCaseInput): Promise<Case> {
        if (this.processError) {
            try {
                const result = await this.actor.submitCase(to_candid_CreateCaseInput_n43(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Case_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitCase(to_candid_CreateCaseInput_n43(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Case_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitSupplyRequest(arg0: CreateSupplyRequestInput): Promise<SupplyRequest> {
        if (this.processError) {
            try {
                const result = await this.actor.submitSupplyRequest(arg0);
                return from_candid_SupplyRequest_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitSupplyRequest(arg0);
            return from_candid_SupplyRequest_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCase(arg0: CaseId, arg1: UpdateCaseInput): Promise<Case | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCase(arg0, to_candid_UpdateCaseInput_n45(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCase(arg0, to_candid_UpdateCaseInput_n45(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSupplyRequestStatus(arg0: SupplyRequestId, arg1: SupplyRequestStatus): Promise<SupplyRequest | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSupplyRequestStatus(arg0, to_candid_SupplyRequestStatus_n49(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSupplyRequestStatus(arg0, to_candid_SupplyRequestStatus_n49(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_BusinessType_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BusinessType): BusinessType {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_CaseStatus_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaseStatus): CaseStatus {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Case_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Case): Case {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Expert_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Expert): Expert {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_ResourceCategory_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ResourceCategory): ResourceCategory {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Resource_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Resource): Resource {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Specialization_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Specialization): Specialization {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_SupplyRequestStatus_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SupplyRequestStatus): SupplyRequestStatus {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_SupplyRequest_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SupplyRequest): SupplyRequest {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Case]): Case | null {
    return value.length === 0 ? null : from_candid_Case_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExpertId]): ExpertId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Expert]): Expert | null {
    return value.length === 0 ? null : from_candid_Expert_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Resource]): Resource | null {
    return value.length === 0 ? null : from_candid_Resource_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SupplyRequest]): SupplyRequest | null {
    return value.length === 0 ? null : from_candid_SupplyRequest_n31(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ResourceId;
    name: string;
    isAvailable: boolean;
    description: string;
    category: _ResourceCategory;
}): {
    id: ResourceId;
    name: string;
    isAvailable: boolean;
    description: string;
    category: ResourceCategory;
} {
    return {
        id: value.id,
        name: value.name,
        isAvailable: value.isAvailable,
        description: value.description,
        category: from_candid_ResourceCategory_n15(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    name: string;
    createdAt: _Timestamp;
    businessType: _BusinessType;
    mobile: string;
    location: string;
}): {
    id: UserId;
    name: string;
    createdAt: Timestamp;
    businessType: BusinessType;
    mobile: string;
    location: string;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        businessType: from_candid_BusinessType_n20(_uploadFile, _downloadFile, value.businessType),
        mobile: value.mobile,
        location: value.location
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _CaseId;
    status: _CaseStatus;
    userId: _UserId;
    createdAt: _Timestamp;
    businessType: _BusinessType;
    description: string;
    photoUrl: [] | [string];
    updatedAt: _Timestamp;
    assignedExpertId: [] | [_ExpertId];
    adminNotes: [] | [string];
}): {
    id: CaseId;
    status: CaseStatus;
    userId: UserId;
    createdAt: Timestamp;
    businessType: BusinessType;
    description: string;
    photoUrl?: string;
    updatedAt: Timestamp;
    assignedExpertId?: ExpertId;
    adminNotes?: string;
} {
    return {
        id: value.id,
        status: from_candid_CaseStatus_n24(_uploadFile, _downloadFile, value.status),
        userId: value.userId,
        createdAt: value.createdAt,
        businessType: from_candid_BusinessType_n20(_uploadFile, _downloadFile, value.businessType),
        description: value.description,
        photoUrl: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.photoUrl)),
        updatedAt: value.updatedAt,
        assignedExpertId: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.assignedExpertId)),
        adminNotes: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.adminNotes))
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _SupplyRequestId;
    status: _SupplyRequestStatus;
    resourceId: _ResourceId;
    userId: _UserId;
    createdAt: _Timestamp;
    deliveryLocation: string;
    quantity: bigint;
}): {
    id: SupplyRequestId;
    status: SupplyRequestStatus;
    resourceId: ResourceId;
    userId: UserId;
    createdAt: Timestamp;
    deliveryLocation: string;
    quantity: bigint;
} {
    return {
        id: value.id,
        status: from_candid_SupplyRequestStatus_n33(_uploadFile, _downloadFile, value.status),
        resourceId: value.resourceId,
        userId: value.userId,
        createdAt: value.createdAt,
        deliveryLocation: value.deliveryLocation,
        quantity: value.quantity
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ExpertId;
    contactInfo: string;
    assignedCasesCount: bigint;
    name: string;
    createdAt: _Timestamp;
    isActive: boolean;
    specialization: _Specialization;
}): {
    id: ExpertId;
    contactInfo: string;
    assignedCasesCount: bigint;
    name: string;
    createdAt: Timestamp;
    isActive: boolean;
    specialization: Specialization;
} {
    return {
        id: value.id,
        contactInfo: value.contactInfo,
        assignedCasesCount: value.assignedCasesCount,
        name: value.name,
        createdAt: value.createdAt,
        isActive: value.isActive,
        specialization: from_candid_Specialization_n7(_uploadFile, _downloadFile, value.specialization)
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    poultry: null;
} | {
    fish: null;
} | {
    goat: null;
} | {
    seeds: null;
}): ResourceCategory {
    return "poultry" in value ? ResourceCategory.poultry : "fish" in value ? ResourceCategory.fish : "goat" in value ? ResourceCategory.goat : "seeds" in value ? ResourceCategory.seeds : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
}): CaseStatus {
    return "pending" in value ? CaseStatus.pending : "completed" in value ? CaseStatus.completed : "inProgress" in value ? CaseStatus.inProgress : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    delivered: null;
} | {
    processing: null;
}): SupplyRequestStatus {
    return "cancelled" in value ? SupplyRequestStatus.cancelled : "pending" in value ? SupplyRequestStatus.pending : "delivered" in value ? SupplyRequestStatus.delivered : "processing" in value ? SupplyRequestStatus.processing : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fishery: null;
} | {
    goatFarming: null;
} | {
    poultry: null;
} | {
    agriculture: null;
}): BusinessType {
    return "fishery" in value ? BusinessType.fishery : "goatFarming" in value ? BusinessType.goatFarming : "poultry" in value ? BusinessType.poultry : "agriculture" in value ? BusinessType.agriculture : value;
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Case>): Array<Case> {
    return value.map((x)=>from_candid_Case_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SupplyRequest>): Array<SupplyRequest> {
    return value.map((x)=>from_candid_SupplyRequest_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Expert>): Array<Expert> {
    return value.map((x)=>from_candid_Expert_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Resource>): Array<Resource> {
    return value.map((x)=>from_candid_Resource_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n18(_uploadFile, _downloadFile, x));
}
function to_candid_BusinessType_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BusinessType): _BusinessType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_CaseStatus_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CaseStatus): _CaseStatus {
    return to_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function to_candid_CreateCaseInput_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateCaseInput): _CreateCaseInput {
    return to_candid_record_n44(_uploadFile, _downloadFile, value);
}
function to_candid_CreateExpertInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateExpertInput): _CreateExpertInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_CreateResourceInput_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateResourceInput): _CreateResourceInput {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_ResourceCategory_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResourceCategory): _ResourceCategory {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_SaveProfileInput_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SaveProfileInput): _SaveProfileInput {
    return to_candid_record_n41(_uploadFile, _downloadFile, value);
}
function to_candid_Specialization_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Specialization): _Specialization {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_SupplyRequestStatus_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SupplyRequestStatus): _SupplyRequestStatus {
    return to_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateCaseInput_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateCaseInput): _UpdateCaseInput {
    return to_candid_record_n46(_uploadFile, _downloadFile, value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    isAvailable: boolean;
    description: string;
    category: ResourceCategory;
}): {
    name: string;
    isAvailable: boolean;
    description: string;
    category: _ResourceCategory;
} {
    return {
        name: value.name,
        isAvailable: value.isAvailable,
        description: value.description,
        category: to_candid_ResourceCategory_n11(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contactInfo: string;
    name: string;
    specialization: Specialization;
}): {
    contactInfo: string;
    name: string;
    specialization: _Specialization;
} {
    return {
        contactInfo: value.contactInfo,
        name: value.name,
        specialization: to_candid_Specialization_n3(_uploadFile, _downloadFile, value.specialization)
    };
}
function to_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    businessType: BusinessType;
    mobile: string;
    location: string;
}): {
    name: string;
    businessType: _BusinessType;
    mobile: string;
    location: string;
} {
    return {
        name: value.name,
        businessType: to_candid_BusinessType_n42(_uploadFile, _downloadFile, value.businessType),
        mobile: value.mobile,
        location: value.location
    };
}
function to_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    businessType: BusinessType;
    description: string;
    photoUrl?: string;
}): {
    businessType: _BusinessType;
    description: string;
    photoUrl: [] | [string];
} {
    return {
        businessType: to_candid_BusinessType_n42(_uploadFile, _downloadFile, value.businessType),
        description: value.description,
        photoUrl: value.photoUrl ? candid_some(value.photoUrl) : candid_none()
    };
}
function to_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status?: CaseStatus;
    assignedExpertId?: ExpertId;
    adminNotes?: string;
}): {
    status: [] | [_CaseStatus];
    assignedExpertId: [] | [_ExpertId];
    adminNotes: [] | [string];
} {
    return {
        status: value.status ? candid_some(to_candid_CaseStatus_n47(_uploadFile, _downloadFile, value.status)) : candid_none(),
        assignedExpertId: value.assignedExpertId ? candid_some(value.assignedExpertId) : candid_none(),
        adminNotes: value.adminNotes ? candid_some(value.adminNotes) : candid_none()
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResourceCategory): {
    poultry: null;
} | {
    fish: null;
} | {
    goat: null;
} | {
    seeds: null;
} {
    return value == ResourceCategory.poultry ? {
        poultry: null
    } : value == ResourceCategory.fish ? {
        fish: null
    } : value == ResourceCategory.goat ? {
        goat: null
    } : value == ResourceCategory.seeds ? {
        seeds: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BusinessType): {
    fishery: null;
} | {
    goatFarming: null;
} | {
    poultry: null;
} | {
    agriculture: null;
} {
    return value == BusinessType.fishery ? {
        fishery: null
    } : value == BusinessType.goatFarming ? {
        goatFarming: null
    } : value == BusinessType.poultry ? {
        poultry: null
    } : value == BusinessType.agriculture ? {
        agriculture: null
    } : value;
}
function to_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CaseStatus): {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
} {
    return value == CaseStatus.pending ? {
        pending: null
    } : value == CaseStatus.completed ? {
        completed: null
    } : value == CaseStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SupplyRequestStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    delivered: null;
} | {
    processing: null;
} {
    return value == SupplyRequestStatus.cancelled ? {
        cancelled: null
    } : value == SupplyRequestStatus.pending ? {
        pending: null
    } : value == SupplyRequestStatus.delivered ? {
        delivered: null
    } : value == SupplyRequestStatus.processing ? {
        processing: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
